name: oilnote
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  meta: ^1.1.6
  equatable: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  bloc_test: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
        - asset: fonts/Comfortaa-Medium.ttf
        - asset: fonts/Comfortaa-Light.ttf
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-SemiBold.ttf